### ISSUE TITLE
Blaze doesn't run on Java 9

### ISSUE THREAD

**Issue by TobseF** [fizzed/blaze#14]
When I run balze on Windows with a installed Java 9 it crashes on start:

`[INFO] Resolving dependencies...
[INFO] Resolved dependencies in 561 ms
[ERROR] Only classloaders of type URLClassLoader supported
java.lang.IllegalArgumentException: Only classloaders of type URLClassLoader supported
        at com.fizzed.blaze.internal.ClassLoaderHelper.requireURLClassLoader(ClassLoaderHelper.java:46)
        at com.fizzed.blaze.internal.ClassLoaderHelper.addClassPath(ClassLoaderHelper.java:61)
        at com.fizzed.blaze.internal.ClassLoaderHelper.addClassPath(ClassLoaderHelper.java:53)
        at com.fizzed.blaze.core.Blaze$Builder.lambda$loadDependencies$0(Blaze.java:285)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at com.fizzed.blaze.core.Blaze$Builder.loadDependencies(Blaze.java:284)
        at com.fizzed.blaze.core.Blaze$Builder.build(Blaze.java:324)
        at com.fizzed.blaze.cli.Bootstrap.buildBlaze(Bootstrap.java:211)
        at com.fizzed.blaze.cli.Bootstrap.run(Bootstrap.java:140)
        at com.fizzed.blaze.cli.Bootstrap.run(Bootstrap.java:54)
        at com.fizzed.blaze.cli.Bootstrap.main(Bootstrap.java:42)`

The `URLClassLoader` isn't supported anymore in Java 9.

[More info for Java 9 migration and classloader](https://stackoverflow.com/questions/46694600/java-9-compatability-issue-with-classloader-getsystemclassloader) and [Casting To URL Class Loader
](https://blog.codefx.org/java/java-9-migration-guide/)

**Comment by jjlauer** [comment]
Cleaning up old issues.  This was addressed in recent blaze versions.
