### ISSUE TITLE
Compiler path error

### ISSUE THREAD

**Issue by aplatypus** [fizzed/blaze#2]
I used wget to download the `blaze` jar file on Windows:

    wget -O blaze.jar 'http://repo1.maven.org/maven2/com/fizzed/blaze-lite/0.14.0/blaze-lite-0.14.0.jar'

And made the example "hello world" Java file in the same directory.  I set JAVA_HOME to point to the Java 8 u102 JDK folder.  I get compile errors when I attempt to run hello world:

        public class blaze {

            public void main() {
                System.out.println("Hello World!");
            }

        }

When I fire the Jar file I see this error ...
*  [ERROR] **Unable to get or create path to compile classes**

Command line session 

        d:> DIR
         Volume in drive D is win

        22-Sep-2016  09:25         1,806,644 blaze.jar
        22-Sep-2016  09:26               113 blaze.java

        d:> echo %JAVA_HOME%
        b:\lang\java\jdk\v1.8\u102\x64

        d:> java -jar blaze.jar
        [INFO] Resolving dependencies...
        [INFO] Resolved dependencies in 14 ms
        [INFO] Compiling script...
        [ERROR] Unable to get or create path to compile classes
        com.fizzed.blaze.core.BlazeException: Unable to get or create path to compile classes
                at com.fizzed.blaze.jdk.BlazeJdkEngine.compile(BlazeJdkEngine.java:88)
                at com.fizzed.blaze.jdk.BlazeJdkEngine.compile(BlazeJdkEngine.java:43)
                at com.fizzed.blaze.core.Blaze$Builder.compileScript(Blaze.java:314)
                at com.fizzed.blaze.core.Blaze$Builder.build(Blaze.java:322)
                at com.fizzed.blaze.cli.Bootstrap.buildBlaze(Bootstrap.java:203)
                at com.fizzed.blaze.cli.Bootstrap.run(Bootstrap.java:132)
                at com.fizzed.blaze.cli.Bootstrap.run(Bootstrap.java:54)
                at com.fizzed.blaze.cli.Bootstrap.main(Bootstrap.java:42)
        Caused by: java.nio.file.NoSuchFileException: \Users\wmason\.blaze
                at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
                at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
                at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
                at sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source)
                at java.nio.file.Files.createDirectory(Unknown Source)
                at com.fizzed.blaze.internal.ConfigHelper.userBlazeDir(ConfigHelper.java:138)
                at com.fizzed.blaze.internal.ConfigHelper.userBlazeEngineDir(ConfigHelper.java:155)
                at com.fizzed.blaze.internal.ConfigHelper.userBlazeEngineScriptClassesDir(ConfigHelper.java:182)
                at com.fizzed.blaze.jdk.BlazeJdkEngine.compile(BlazeJdkEngine.java:76)
                ... 7 more

Evidently I need to set-up some further config or specify something more to get things running.

Also I've added the blaze plugin for Netbeans, but I can't see anything in the Netbeans Options to do any set-up for the plugin.

This issue seems like a documentation thing, it would be _nice_ though if it worked like the readme says.

**Comment by jjlauer** [comment]
Does this work?  Where you pass the actual script you want to execute vs.
the default.

java -jar blaze.jar blaze.java

**Comment by aplatypus** [comment]
OK that makes some sense -- This is windows 10 and we had user issues when we first _down_-graded.

The script should use one of the following...
      APPDATA=C:\Users\wmason\AppData\Roaming
      LOCALAPPDATA=C:\Users\wmason\AppData\Local
      TEMP=z:\$$$\wmason
      TMP=z:\$$$\wmason
      USERPROFILE=C:\Users\wmason

It looks like it is using:

      HOMEPATH=\Users\wmason

Which is setup by docker or by msys I think.  For this kind of thing; I'd think the appropriate place to compile to is the TMP area.

I looked through the environment, windows 10 doesn't seem to have a "home" it self.  HOMEPATH is a linux compatibility thing, not for windows.

**Comment by jjlauer** [comment]
Can you give v0.14.1 a try?  Released it last night.

**Comment by aplatypus** [comment]
I have run with the newer version, to confirm the file used:

` wget -O blaze.jar 'http://repo1.maven.org/maven2/com/fizzed/blaze-lite/0.14.1/blaze-lite-0.14.1.jar'`

Version string:
```
java -jar blaze.jar --version
blaze: v0.14.1 (commit 9979cfea @ 2016-09-22T02:15:15.877Z)
 by Fizzed, Inc. (http://fizzed.com)
 at https://github.com/fizzed/blaze
```

I got a **NullPointerException** this time with both versions of the command (output below).
*  java -jar blaze.jar 
*  java -jar blaze.jar blaze.java

Looking at the earlier comment about the home drive.  Commonly on Windows people keep things on their system (C:\) drive.  Our projects are NOT on the C-drive for lots of reasons.  

I would recommend expanding the **%TMP%** environment variable for the build path.  I like this personally because I do not want to have to back-up lots of temporary files from inside the settings folder tree.

```
d:> java -jar blaze.jar
[ERROR] null
java.lang.NullPointerException
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.nio.file.Paths.get(Unknown Source)
        at com.fizzed.blaze.internal.ContextImpl.dirIfExists(ContextImpl.java:169)
        at com.fizzed.blaze.internal.ContextImpl.findUserDir(ContextImpl.java:151)
        at com.fizzed.blaze.internal.ContextImpl.<init>(ContextImpl.java:50)
        at com.fizzed.blaze.core.Blaze$Builder.configure(Blaze.java:215)
        at com.fizzed.blaze.core.Blaze$Builder.resolveDependencies(Blaze.java:226)
        at com.fizzed.blaze.core.Blaze$Builder.loadDependencies(Blaze.java:275)
        at com.fizzed.blaze.core.Blaze$Builder.build(Blaze.java:320)
        at com.fizzed.blaze.cli.Bootstrap.buildBlaze(Bootstrap.java:203)
        at com.fizzed.blaze.cli.Bootstrap.run(Bootstrap.java:132)
        at com.fizzed.blaze.cli.Bootstrap.run(Bootstrap.java:54)
        at com.fizzed.blaze.cli.Bootstrap.main(Bootstrap.java:42)

d:> java -jar blaze.jar blaze.java
[ERROR] null
java.lang.NullPointerException
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.nio.file.Paths.get(Unknown Source)
        at com.fizzed.blaze.internal.ContextImpl.dirIfExists(ContextImpl.java:169)
        at com.fizzed.blaze.internal.ContextImpl.findUserDir(ContextImpl.java:151)
        at com.fizzed.blaze.internal.ContextImpl.<init>(ContextImpl.java:50)
        at com.fizzed.blaze.core.Blaze$Builder.configure(Blaze.java:215)
        at com.fizzed.blaze.core.Blaze$Builder.resolveDependencies(Blaze.java:226)
        at com.fizzed.blaze.core.Blaze$Builder.loadDependencies(Blaze.java:275)
        at com.fizzed.blaze.core.Blaze$Builder.build(Blaze.java:320)
        at com.fizzed.blaze.cli.Bootstrap.buildBlaze(Bootstrap.java:203)
        at com.fizzed.blaze.cli.Bootstrap.run(Bootstrap.java:132)
        at com.fizzed.blaze.cli.Bootstrap.run(Bootstrap.java:54)
        at com.fizzed.blaze.cli.Bootstrap.main(Bootstrap.java:42)
```

**Comment by aplatypus** [comment]
Hi ...

Just a thought, is there a command line option to specify the class/build directory when I use Blaze?

w.

**Comment by jjlauer** [comment]
No. The files Blaze compiles should be semi-permanently stored between
runs.  They are identical to what maven or gradle do w/ dependencies.
Those aren't downloaded to a temp directory, rather they are downloaded to
a directory in your home dir.  Blaze uses the same concept.  It's how Blaze
gets scripts to run quickly if you haven't made any changes to a script.
There are also longer terms plans to use that directory for other things
too -- so its not a temp directory.

Have you tried cloning the repo and running "mvn test" on it?

-Joe

**Comment by aplatypus** [comment]
Hi ...

Just a thought, is there a command line option to specify the class/build directory when I use Blaze?

w.

**Comment by aplatypus** [comment]
I see.  In that case can it just use maven?  There will never be a "home" folder on the D: drive in this lab.  That is a windows thing, they want home on the system drive and all our projects are on a separate disk area.

One other wrinkle, if files are cached that's OK but when one is working off-line does that mean you need to ensure the Blaze cache/repository is up-to-date?

**Comment by jjlauer** [comment]
Give the new v0.15.0 a try.

**Comment by aplatypus** [comment]
Hi, I finally found an opportunity to try the v0.15 build.
```
>  Give the new v0.15.0 a try
```
The usual JAVA_HOME on our PC-s will always be the JRE 

To use a JDK I need to set:
*  JAVA_HOME 
To point to the current JDK -- Which I did initially.  I've recorded that with the initial bug report (above).

The Blaze v0.15 build gives the following output.  Apparently it won't look at the JAVA_HOME environment variable.
```
d:> java -jar blaze.jar
[INFO] Resolving dependencies...
[INFO] Resolved dependencies in 38 ms
[INFO] Compiling script...
[ERROR] Unable to compile blaze.java to a class file.
 The system java compiler is missing (are you running a JRE rather than a JDK?)
 Either run this with a JDK or add "org.eclipse.jdt.core.compiler:ecj:<version>" to blaze.dependencies.

d:> echo %JAVA_HOME%
b:\lang\java\jdk\v1.8\u102\x64
```

I called-up the JDK installed JAVA and it works!
```
d:>  %JAVA_HOME%\bin\java -jar blaze.jar
[INFO] Resolving dependencies...
[INFO] Resolved dependencies in 17 ms
[INFO] Compiling script...
[INFO] Compiled script in 29 ms
[INFO] Executing blaze.java:main...
Hello World!
[INFO] Executed blaze.java:main in 1 ms
[INFO] Blazed in 198 ms
```
If one roots around Oracle's words, they have many many words, you'll find Oracle stopped using JAVA_HOME some time ago, which is a great inconvenience.  So you'll need to let people know they may need to do something like:
```
%JDK_HOME%\java -jar blaze.jar
```
If they are not running an insecure JDK as their Java platform.
